### ISSUE TITLE
Upgrade to Swift 4.2

### ISSUE THREAD

**Issue by annjose** [microsoft/appcenter-sampleapp-ios-swift#49]
The project is on Swift 3 and hence Xcode 10 shows the warning that it can be upgraded.

The warning can be fixed by upgrading to Swift 4.2

**Comment by vyasknellutla** [comment]
Hi @annjose ,

Terribly sorry for the delay, but since then we've undergone a revamp of all the sample applications and got them updated to the latest standards and dependencies (in this case Swift 5).

I'm closing this issue for now, but do let us know if we have other issues with the repository and we'll be happy to address them.
